'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Check, Copy, Menu, Moon, Play, Sun, X } from 'lucide-react'
import { DenielAssistant } from '@/components/deniel-assistant'
import { SiteEffects } from '@/components/site-effects'

const projects = [
  { title: 'Asiana Airlines PTFS', type: 'Official airline website', year: '2026', color: 'emerald', description: 'The official website of Asiana Airlines PTFS, built with care for a community aviation project.', url: 'https://github.com/aetherspace-a/Asiana-PTFS-Website' },
  { title: 'AsianaPTFS-VAMS', type: 'Discord bot + web dashboard', year: '2026', color: 'coral', description: 'An all-in-one virtual airline operations platform for pilots, staff, and administrators.', url: 'https://github.com/aetherspace-a/AsianaPTFS-VAMS' },
  { title: 'AAR Utilities', type: 'Flight operations suite', year: '2026', color: 'mint', description: 'Real-time aviation data, voice announcements, and automated XP leveling for Asiana Airlines PTFS.', url: 'https://github.com/aetherspace-a/AAR-Utilities' },
  { title: 'aetherspacetime', type: 'Personal web experiment', year: '2026', color: 'emerald', description: 'An in-bio website inspired by mytimeis, designed as a small personal space on the web.', url: 'https://github.com/aetherspace-a/aetherspacetime' },
]
const tools = ['JavaScript', 'Python', 'HTML5', 'Next.js', 'Discord Bots', 'Databases', 'GitHub', 'Vercel']
const timeline = [['Now', 'Student developer from the Philippines focused on full stack development, Discord bots, automation, and modern web applications.'], ['Building', 'Web applications and Discord bots that solve practical problems for real communities.'], ['Learning', 'Backend engineering, APIs, databases, cloud, and DevOps.'], ['Open to', 'Open source collaboration, student developer opportunities, web development, and backend work.']]

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`reveal ${className}`}>{children}</div> }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [dark, setDark] = useState(false)
  const [selectedProject, setSelectedProject] = useState<typeof projects[number] | null>(null)
  const [copied, setCopied] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  const nav = useMemo(() => [['about', 'About'], ['work', 'Work'], ['contact', 'Contact']], [])
  const copyEmail = async () => { await navigator.clipboard?.writeText('hello@deniel.lol'); setCopied(true); setTimeout(() => setCopied(false), 1800) }
  return <><SiteEffects /><main className="site-shell">
    <header className="site-nav"><a href="#top" className="wordmark">DENIEL<span>.</span></a><nav className={menuOpen ? 'is-open' : ''}>{nav.map(([id, label]) => <a href={`#${id}`} key={id} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><div className="nav-actions"><button className="icon-button" aria-label="Toggle color theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={16} /> : <Moon size={16} />}</button><a href="#contact" className="nav-contact">Let&apos;s talk <ArrowUpRight size={14} /></a><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <section id="top" className="hero section-pad" data-reveal><div className="hero-top"><p className="eyebrow">Portfolio / 2026</p><p className="availability"><i /> Available for useful work</p></div><div className="hero-grid"><div><p className="hero-kicker">Student developer<br />from the Philippines.</p><h1>Deniel<br /><em>John</em><br />Prado<span className="hero-dot">.</span></h1></div><div className="hero-intro"><p>I build practical software across full stack web apps, Discord bots, automation, and modern digital experiences.</p><a className="circle-link" href="#work" aria-label="Explore selected work"><ArrowUpRight size={27} /></a></div></div><div className="hero-ticker"><span>Build with care</span><span>Think in systems</span><span>Leave room for play</span><span>Build with care</span></div></section>
    <section id="about" className="about section-pad" data-reveal><div className="section-label"><span>01</span><span>About the work</span></div><div className="about-grid"><Reveal><h2>Useful things,<br /><em>with a pulse.</em></h2></Reveal><Reveal><div className="about-copy"><p className="lead">I&apos;m a student developer who likes turning ideas into useful software.</p><p>My work moves between frontend development, backend systems, documentation, automation, and community tools. I care about practical solutions, clear systems, and software that helps people do more.</p><a className="text-link" href="#contact">More about the practice <ArrowUpRight size={15} /></a></div></Reveal></div></section>
    <section className="timeline section-pad" data-reveal><div className="section-label"><span>02</span><span>A short timeline</span></div><div className="timeline-list" data-stagger>{timeline.map(([year, text], index) => <Reveal key={year}><div className="timeline-row"><span className="timeline-year">{year}</span><span className="timeline-dot" /><p>{text}</p><span className="timeline-index">0{index + 1}</span></div></Reveal>)}</div></section>
    <section className="tools section-pad" data-reveal><div className="section-label"><span>03</span><span>Tools &amp; stacks</span></div><div className="tools-heading"><h2>A toolkit for<br /><em>useful software.</em></h2><p>Full stack foundations for web apps, Discord bots, APIs, databases, and cloud systems.</p></div><div className="tools-list">{tools.map((tool, index) => <div className="tool-row" key={tool}><span className="tool-index">0{index + 1}</span><span className="tool-name">{tool}</span><span className="tool-mark">+</span></div>)}</div></section>
    <section id="work" className="work section-pad" data-reveal><div className="section-label"><span>04</span><span>Selected work</span></div><div className="work-heading"><h2>Built for<br /><em>real communities.</em></h2><p>Selected projects from Asiana Airlines PTFS, aviation operations, personal web experiments, and community tooling.</p></div><div className="project-grid" data-stagger>{projects.map((project, index) => <Reveal key={project.title}><button className={`project-card ${project.color}`} onClick={() => setSelectedProject(project)}><div className="project-art"><span>{String(index + 1).padStart(2, '0')}</span><div className="art-shape" /></div><div className="project-meta"><span>{project.type}</span><span>{project.year}</span></div><h3>{project.title}</h3><span className="project-arrow"><ArrowUpRight size={20} /></span></button></Reveal>)}</div></section>
    <section className="music section-pad" data-reveal><div className="section-label"><span>05</span><span>Currently listening</span></div><div className="music-layout"><div><h2>Somewhere<br />between<br /><em>focus &amp; feeling.</em></h2><div className="music-provider-links"><a className="play-button" href="https://open.spotify.com/artist/0hShtOro50E68407ZrT06D" target="_blank" rel="noreferrer"><Play size={15} fill="currentColor" /> Open Spotify</a><a className="provider-link" href="https://www.youtube.com/@zeopspacemusic" target="_blank" rel="noreferrer">YouTube Music <ArrowUpRight size={14} /></a></div></div><div className="record"><div className="record-info"><p className="eyebrow">Now playing</p><h3>zeopspace radio</h3><p>Official player from the artist&apos;s Spotify catalog.</p><iframe className="music-embed" src="https://open.spotify.com/embed/artist/0hShtOro50E68407ZrT06D?utm_source=generator&theme=0" title="zeopspace on Spotify" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" /></div></div></div></section>
    <section id="contact" className="contact section-pad" data-reveal><div className="section-label"><span>06</span><span>Start a conversation</span></div><div className="contact-grid"><div><h2>Have a good<br /><em>question?</em></h2><p>I&apos;m open to open source collaboration, student developer opportunities, web development, Discord bots, and backend work.</p><div className="contact-actions"><button className="email-pill" onClick={copyEmail}>{copied ? <Check size={15} /> : <Copy size={15} />} {copied ? 'Copied' : 'hello@deniel.lol'}</button><div className="social-links"><a href="https://github.com/aetherspace-a" aria-label="GitHub">GH</a><a href="https://haunt.gg/zeop" aria-label="Personal website">web</a><a href="https://github.com/aetherspace-a" aria-label="Open source profile">os</a></div></div></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" placeholder="What are you working on?" rows={4} /></label><button className="submit-button" type="submit">{submitted ? 'Message ready' : 'Send a note'} <ArrowUpRight size={17} /></button></form></div></section>
    <footer className="site-footer"><span>© 2026 Deniel John Prado</span><a href="#top">Back to top <ArrowUpRight size={14} /></a><span>Built with intention.</span></footer><DenielAssistant />
    {selectedProject && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-label={selectedProject.title} onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedProject(null)} aria-label="Close project"><X size={20} /></button><div className={`modal-art ${selectedProject.color}`}><span>Selected work</span><b>{selectedProject.title}</b></div><p className="eyebrow">{selectedProject.type} / {selectedProject.year}</p><h2>{selectedProject.title}</h2><p>{selectedProject.description}</p><a className="text-link" href={selectedProject.url} target="_blank" rel="noreferrer">View on GitHub <ArrowUpRight size={15} /></a></div></div>}
  </main></>
}
